services:
  niord:
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    build: ./Server
    image: niord
    ports: ["8000:80"]
    env_file: ./server/.env
    container_name: server

  redis:
    build: ./Redis
    image: redis 
    env_file: ./Redis/.env
    container_name: redis_db 
  db:
    image: postgres
    env_file: ./.env
    container_name: database
  waha:
    image: devlikeapro/waha:latest
    env_file: ./waha/.env
    container_name: waha
    ports:
      - "3000:3000"
    volumes:
      - waha_session_data:/app/.sessions

volumes:
  waha_session_data:
